### ISSUE TITLE
Roadmap - Task List

### ISSUE THREAD

**Issue by swarnimarun** [premAI-io/benchmarks#5]
## Minor fixes:
- [x] Fix the supported features table, to better reflect reality.
- [ ] Cleanup the code and ensure names for user exposed ENV variables are consistent.
- [ ] Handle quantization information, and provide info regarding quantization method used across models and scripts in the README. (llama.cpp quantization vs tinygrad vs CTranslate2 vs GPTQ)
- [ ] Provide more CLI options for running individual scripts with other models as well. For testing frameworks on systems with less memory.

## Feature(in order of priority):
- [ ] Add custom model runner code, for running benchmarks and provide hooks for directly reporting performance metrics into as an output.
- [ ] Setup scripts for running benchmarks with a single command and getting proper performance reports.
- [ ] Improve caching for models, currently some scripts will end up redownloading the models, which has already been fixed for some.
- [ ] Simplify running for any specific platform(nvidia/mac), with any supported model.
- [ ] Auto-setup rust, python, git and etc, for the user before running the benchmark(low priority).
